### ISSUE TITLE
ERROR: YOUR PATHNAME GOES HERE/LiverQuantF.json (No such file or directory) in Fibrosis intensity script.groovy at line number 32

### ISSUE THREAD

**Issue by Kan-E** [DominickHellen/Karpen-Lab-Liver-Quant-2022#1]
Thank you very much for developing the excellent tool.

I followed the method described in the paper (https://en.bio-protocol.org/en/bpdetail?id=4776&type=0) and executed the Fibrosis intensity script. However, I encountered the following error:

ERROR: YOUR PATHNAME GOES HERE/LiverQuantF.json (No such file or directory) in Fibrosis intensity script.groovy at line number 32

It appears that DominickHellen/LiverQuant does not contain a file named LiverQuantF.json. Could you please provide guidance on how to obtain the LiverQuantF.json file?

Thank you in advance for your assistance.

**Comment by DominickHellen** [comment]
Hi Kan,

Thank you for using my protocol! 

The LiverQuantF.json file _is_ generated from running the Fibrosis intensity script.groovy, where the command write (.write(newConfig, "utf-8")) is used at the end of line 32. As a note, make sure to fill out your pathname in lines 25-32 in the intensity script. If the script keeps producing errors however, there is an alternative to generate the 'LiverQuantF.json' file:

You can generate your own 'LiverQuantF.json' file by following **Section H** of the bio-protocol paper (Self-thresholding for fibrosis and macrophages detection within QuPath). This is a very fast and simple approach to generating the .json file. Be sure to follow the directions carefully, and name the classifier 'LiverQuantF'. This will ensure that the fibrosis detection script works. 

Please do not hesitate if you have any additional issues or problems. You can reach me at dominick.hellen@emory.edu if you have any troubles with the protocol.

Best,
Dominick

**Comment by Kan-E** [comment]
Hi Dominick,

Thank you for your prompt response.
I have confirmed that it is working without any issues.
Thank you for your support.

Regards,

Kan
